requires "Mojolicious", ">= 9.33";
requires "aliased", ">= 0.34";
requires "Otogiri", ">= 0.19";
requires "Type::Tiny", ">= 2.004000";
requires "Type::Alias", ">= 0.06";
requires "Function::Parameters", ">= 2.002004";
requires "DBD::SQLite", ">= 1.72";

on 'test' => sub {
  requires "Test2::Suite", ">= 0.000155";
};